name:                hudoku-core
version:             0.1.0.0
github:              "boiko-danylo/hudoku"
license:             BSD3
author:              "Daniil Boiko"
maintainer:          "5n00p4eg@gmail.com"
copyright:           "2021 Daniil Boiko"

synopsis:            Structure-based sudoku solver core
description:         See DESIGN.md at the repository root.

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- boxes
- extra
- mtl
- text
- bytestring
- aeson
- containers

library:
  source-dirs: src

executables:
  exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - boxes
      - hudoku-core
      - extra

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - hudoku-core
      - boxes
      - HUnit
      - tasty
      - tasty-hunit
